/**
 *
 * Layout Component
 *
 * @version 1.0.0
 * @author [Bryan Lemus](https://github.com/bryanlemus)
 */

// Imports
import React, { ReactNode } from "react";
import logo from "../public/logoipsum-logo-55.svg";
import Head from "next/head";
import Navbar from "./Navbar";
import ActionButton from "../components/ActionButton";
import TextBox from "../components/TextBox";
import Button from "../components/Button";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import SignUp from "../features/authentication/SignUp";

// Types
type props = {
  children?: ReactNode;
  title?: string;
};

// Component
export default function Layout({ children, title }: props) {
  return (
    <div className="Layout">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>{title}</title>
      </Head>
      <Navbar logoSource={logo}>
        <ActionButton text="Hello, Sign in" title="Sign Up">
          <SignUp />
        </ActionButton>
      </Navbar>
      <main>{children}</main>
    </div>
  );
}
